name: Build And Release

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'
  workflow_dispatch:    

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        id: build
        run: |
          python -m PyInstaller --onefile app.py
        shell: bash

      - name: Upload artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-build
          path: dist/app*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Download Ubuntu artifact
      #   if: ${{ needs.build.outputs['ubuntu-latest'].result == 'success' }}
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: app-ubuntu-latest-build
      #     path: ./dist/ubuntu

      - name: Download macOS artifact
        if: ${{ needs.build.outputs['macos-latest'].result == 'success' }}
        uses: actions/download-artifact@v4
        with:
          name: app-macos-latest-build
          path: ./dist/macos

      - name: Download Windows artifact
        if: ${{ needs.build.outputs['windows-latest'].result == 'success' }}
        uses: actions/download-artifact@v4
        with:
          name: app-windows-latest-build
          path: ./dist/windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/ubuntu/*
            ./dist/macos/*
            ./dist/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
